# Generated by Django 4.2.6 on 2023-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0006_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
